homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    path('search', views.search, name='search')
]

login/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'
urlpatterns = [

    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout_view'),
    path('', views.login_view, name='login'),

    path("password_reset/", views.password_reset_request, name="password_reset"),


]

lookup/urls.py
from django.urls import path, include
from . import views

app_name = 'lookup'
urlpatterns = [
    path('', views.index, name='index'),
    path('results', views.results, name='results')
]

syllabus/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include('login.urls')),
    path('syllabus_form/', include('syllabus_form.urls')),
    path('profile/', include('faculty_profile.urls')),
    path('dept_info/', include('dept_info.urls')),
    path('add/', include('synthesizew.urls')),
    path('search/', include('lookup.urls')),

    # Needed for password reset. ONLY WORKS IF THEY ARE IN THE PROJECT URL AND NOT IN APP URL
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="login/password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset/password_reset_complete.html'), name='password_reset_complete'),
]

lookup/models.py
from django.db import models

# Create your models here.

lookup/views.py
from django.shortcuts import render
from synthesizew.models import Syllabus


# Create your views here.
def index(request):
    return render(request, 'lookup/index.html', context={})


def results(request):
    search_by = request.GET.get('dropdown')
    search_results = {}
    if search_by == 'course_title':
        course_title = request.GET.get('search_bar')
        search_results = Syllabus.objects.filter(title__contains=course_title)
    elif search_by == 'instructor_name':
        instructor_name = request.GET.get('search_bar')
        search_results = Syllabus.objects.filter(instructor_name__contains=instructor_name)
    elif search_by == 'course_time':
        course_time = request.GET.get('search_bar')
        search_results = Syllabus.objects.filter(course_time__contains=course_time)
    context = {
        "search_results": search_results
    }
    return render(request, 'lookup/index.html', context=context)

lookup/templates/lookup/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Syllabus Lookup</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script>
        function changePlaceholder() {
            switch(document.getElementById("dropdown").value) {
                case "course_title":
                    document.getElementById("search_bar").placeholder = "Search by course title...";
                    break;
                case "instructor_name":
                    document.getElementById("search_bar").placeholder = "Search by instructor...";
                    break;
                case "course_time":
                    document.getElementById("search_bar").placeholder = "Search by meeting time...";
                    break;
            }
        }
    </script>

    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <img src="">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <h3>UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">

		    <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>
</head>
<body>
    <style>
        body {
        height: 100%;
        align-items: center;
    }

    .lookup {
        width: 30%;
        max-width: 800px;
        padding: 90px;
        margin-left: 600px;
        margin-top: 150px;
        background: #ffc107;
        border-radius: 10px;
    }
    </style>
    <br><br>
    <main class="lookup">
    <div class="container text-left">
        <form action="{% url 'lookup:results' %}" method="get">
            <div>Search by: </div>
            <select id="dropdown" name="dropdown" onchange="changePlaceholder()">
                <option value="course_title">Course title</option>
                <option value="instructor_name">Course instructor</option>
                <option value="course_time">Course times</option>
            </select>
            <div>Please enter the course title here:</div>
            <input name="search_bar" id="search_bar" type="text" placeholder="Search by course title..." />
            <input type="submit" id="submit_click">
        </form>
        <br>
        <br>
        {% for syllabus in search_results %}
            <div id="results_header">Search results:</div>
            <br>
            <li id="results">{{ syllabus.title }}, led by {{ syllabus.instructor_name }} at {{ syllabus.course_time }}</li>
            {% empty %}
            <div>No matches found!</div>
        {% endfor %}

    </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous" />
</body>
</html>