homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    path('search', views.search, name='search')
]

login/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'
urlpatterns = [

    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout_view'),
    path('', views.login_view, name='login'),

    path("password_reset/", views.password_reset_request, name="password_reset"),


]

syllabus/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include('login.urls')),
    path('syllabus_form/', include('syllabus_form.urls')),
    path('profile/', include('faculty_profile.urls')),
    path('dept_info/', include('dept_info.urls')),
    path('add/', include('synthesizew.urls')),
    path('search/', include('lookup.urls')),

    # Needed for password reset. ONLY WORKS IF THEY ARE IN THE PROJECT URL AND NOT IN APP URL
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="login/password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset/password_reset_complete.html'), name='password_reset_complete'),
]

login/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _

# Constant for the types of users (actual value, human readable name)
USER_TYPE = (
    ('student', 'Student'),
    ('faculty', 'Faculty'),
    ('dept', 'Department')
)

# Create your models here.
class MyAccountManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),

        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password=password,

        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True, default="")
    user_type = models.CharField(max_length=10, choices=USER_TYPE, default='student')

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = None
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


    objects = MyAccountManager()
    def __str__(self):
        return self.email
        # For checking permissions. to keep it simple all admin have ALL permissons

    def has_module_perms(self, app_label):
        return True

    # objects = CustomUserManager()

login/forms.py
import self as self
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from login.models import CustomUser


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60)

    class Meta:
        model = CustomUser
        fields = ('email','first_name','last_name','user_type','password1','password2')

login/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.db.models import Q
from django.http import BadHeaderError, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from .forms import AccountAuthenticationForm, UserCreationForm, RegistrationForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def password_reset_request(request):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "login/password_reset/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect('password_reset_done')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="login/password_reset/password_reset.html",
                  context={"password_reset_form": password_reset_form})


def signup(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=password)

            #login(request, account)
            user_type = form.cleaned_data.get('user_type')
            # Department page
            if user_type == 'dept':
                return redirect('/dept_info')

            # Student page -> Not implemented
            elif user_type == 'student':
                return redirect('/')

            # Faculty page
            return redirect('login:login')
        else:
            context['registration_form'] = form
    else:  # Get request
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'login/signup.html', context)


def login_view(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        user_id = user.email.split('@')[0]
        return redirect(reverse('faculty_profile:index', kwargs={'user_id': user_id}))
    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                user_type = user.user_type
                user_id = user.email.split('@')[0]

                if user_type == 'dept':
                    return redirect('/dept_info')

                # Student page -> Not implemented
                elif user_type == 'student':
                    return redirect(reverse('faculty_profile:index', kwargs={'user_id': 'student_id'}))

                # Faculty page
                return redirect(reverse('faculty_profile:index', kwargs={'user_id': user_id}))
   

    else:
        form = AccountAuthenticationForm()
    context['login_form'] = form

    return render(request, 'login/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('homepage:index')

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>Login up</title>
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/login.css'%}"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

	<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
          <h3 >UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
            <a href="{% url 'login:password_reset' %}" class="btn btn-outline-light me-2">Forgot Password</a>
			<a href="{% url 'login:signup' %}" class="btn btn-outline-light me-2">Signup</a>
		    <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>
</head>

<body>

	<main class="form-login">
	  <form method="post">{% csrf_token %}
		<p class="display-5">Login</p>
		<div class="form-floating">
		  	<input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com" autofocus>
			<label for="floatingInput">Email address</label>
		</div>

		<div class="form-floating">
		  	<input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
			<label for="floatingInput">Password</label>

		</div>
		  {% for field in login_form %}
		  	<p>
				{% for error in field.errors %}
					<p style="color: red;">{{error}}</p>
				{% endfor %}
			</p>
		  {% endfor %}
		  {% if login_form.non_field_errors %}
		  	<div style="color:red;">
				<p>{{login_form.non_field_errors}}</p>
			</div>
		  {% endif %}
		<button class="button" type="submit">Log in</button>

	  </form>

	</main>

</body>
</html>

login/templates/login/signup.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>Signup</title>
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/signup.css'%}"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

	<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        <img src="">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <h3>UMBC Syllabus Synthesizer</h3>
        </ul>

        <div class="text-end">

		    <a href="{% url 'login:login' %}" class="btn btn-outline-light me-2">Login</a>
			<a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>
</head>

<body>
	<main class="form-signup">

	  <form method="post">{% csrf_token %}
		<p class="display-6">Create Account</p>

		<div class="form-floating">
		  	<input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com" autofocus>
			<label for="floatingInput">Email address</label>
		</div>

        <div class="form-floating">
		  	<input type="input" name="first_name" class="form-control" id="floatingFirstName" placeholder="John">
			<label for="floatingInput">First Name</label>
		</div>

        <div class="form-floating">
		  	<input type="input" name="last_name" class="form-control" id="floatingLastName" placeholder="Doe">
			<label for="floatingInput">Last Name</label>
		</div>

	  <select class="form-floating" name="user_type" id="user_type">
			<option value="student">Student</option>
		  	<option value="faculty">Faculty</option>
		  	<option value="dept">Department</option>
	  </select>

	  	{% for field in registration_form %}
            <p>
                {% if field.help_text %}
                    <small style="color: gray;">{{field.help_text}}</small>
				{% endif %}
	  	{% endfor %}

		<div class="form-floating">
		  	<input type="password" name="password1" class="form-control" id="floatingPassword1" placeholder="Password">
			<label for="floatingInput">Password</label>
		</div>

	  	<div class="form-floating">
		  	<input type="password" name="password2" class="form-control" id="floatingPassword2" placeholder="Password">
			<label for="floatingInput">Password Confirmation</label>
		</div>


		  {% for field in registration_form %}
            <p>
                {% for error in field.errors %}
                    <p style="color: red">{{error}}</p>
                {% endfor %}
            </p>
        {% endfor %}
		<button class="button" type="submit">Signup</button>

	  </form>
	</main>

</body>
</html>