faculty_profile/urls.py
from django.urls import path

from . import views

app_name = 'faculty_profile'
urlpatterns = [
    # profile index (placeholder, should be deleted in the future)
    path('<str:user_id>/', views.index, name='index'),
    path('<str:user_id>/edit/', views.edit, name='edit'),
    path('<str:user_id>/syllabus/', views.syllabus, name='syllabus')

    # will the login app and corresponding session database provide a faculty's profile_id?
    # path('<int:profile_id>', views.index, name='index'),
    # path('<int:profile_id>/edit/', views.edit, name='edit')
]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    path('search', views.search, name='search')
]

login/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'
urlpatterns = [

    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout_view'),
    path('', views.login_view, name='login'),

    path("password_reset/", views.password_reset_request, name="password_reset"),


]

syllabus/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include('login.urls')),
    path('syllabus_form/', include('syllabus_form.urls')),
    path('profile/', include('faculty_profile.urls')),
    path('dept_info/', include('dept_info.urls')),
    path('add/', include('synthesizew.urls')),
    path('search/', include('lookup.urls')),

    # Needed for password reset. ONLY WORKS IF THEY ARE IN THE PROJECT URL AND NOT IN APP URL
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="login/password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset/password_reset_complete.html'), name='password_reset_complete'),
]

syllabus_form/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView

from . import forms

app_name = 'syllabus_form'
FORMS = [('1', forms.CourseForm1),
         ('2', forms.CourseForm2),
         ('3', forms.CourseForm3),
         ('4', forms.CourseForm4),
         ('5', forms.CourseForm5),
         ('6', forms.CourseForm6),
         ('7', forms.CourseForm7),
         ('8', forms.CourseForm8),
         ('9', forms.CourseForm9),
         ('10', forms.CourseForm10),
         ('11', forms.CourseForm11),
         ('12', forms.CourseForm12),
         ('13', forms.CourseForm13),
         ('14', forms.CourseForm14),
         ('15', forms.CourseForm15),
         ('16', forms.CourseForm16Full),
         ('17', forms.CourseForm17),
         ]
# initial = {'1': {'department': 'IT', 'department_office': 'Room ITE 404', 'department_phone': '111-111-1111', 'course_number': '101', 'course_name':'Intro', 'semester':'Summer', 'year':'2021', 'course_acronym': 'IS'},
                    # '2': {'instructor_name':'Gerson', 'instructor_phone':'111-111-1111', 'instructor_email':'gkroiz1@umbc.edu', 'instructor_fax':'', 'instructor_website':'', 'instructor_course_delivery_site':'Blackboard', 'instructor_office_hours':'M/W 4'}}
urlpatterns = [
    path('wizard/', views.Wizard.as_view(FORMS,)),
    path('wizard/', views.Wizard),
    path('', views.wizardWelcome, name='wizardWelcome')
]

synthesizew/urls.py
from django.urls import path
from . import views


app_name = 'synthesizew'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.add, name='add'),
]

faculty_profile/models.py
from django.db import models


# Create your models here.

# model: Faculty Profile
# attributes: ID, name, email, office phone, office location
class Profile(models.Model):
    faculty_id = models.CharField(max_length=50, primary_key=True)
    location = models.CharField(max_length=100, default='None')
    phone = models.CharField(max_length=20, default='+1 (000) 000-0000')

    def __str__(self):
        return self.faculty_id


class OfficeHours(models.Model):
    faculty = models.ForeignKey(Profile, on_delete=models.CASCADE)
    date_time = models.CharField(max_length=100)

    class Meta:
        ordering = ['faculty_id']

faculty_profile/forms.py
from django import forms
from faculty_profile.models import Profile


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

    faculty_id = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Faculty ID (front of your UMBC email)', 'style': 'width: 350px;', 'class': 'form-control'}))
    location = forms.CharField(widget=forms.TextInput(attrs={'style': 'width: 350px;', 'class': 'form-control'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={ 'style': 'width: 350px;', 'class': 'form-control'}))
    extra_field_count = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        extra_fields = kwargs.pop('extra', 0)

        # check if extra_fields exist. If they don't exist assign 0 to them
        if not extra_fields:
            extra_fields = 0

        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.fields['extra_field_count'].initial = extra_fields

        for index in range(int(extra_fields)):
            # generate extra fields in the number specified via extra_fields
            self.fields['office_hour_field_{index}'.format(index=index + 1)] = forms.CharField(max_length=100)

    def get_fields(self):
        return self.fields

faculty_profile/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from faculty_profile.models import Profile, OfficeHours
from .forms import EditProfileForm


def index(request, user_id):
    # get the id of the logged in user if a user is logged in
    logged_in = False
    user = request.user
    if user.is_authenticated:
        logged_in = user.email.split('@')[0]

    profiles = Profile.objects.filter()

    no_profile = True
    for profile in profiles:
        # if corresponding user is found, retrieve office hours and change flag
        if user_id == profile.faculty_id:
            office_hours = OfficeHours.objects.filter(faculty=user_id)
            no_profile = False
            break

    # if there is NO user logged in and they are visiting a profile that DOES NOT exist
    if logged_in is False and no_profile:
        return render(request, 'faculty_profile/no_login_no_profile.html', context={'user_id': user_id})
    # if there is NO user logged in and they are visiting a profile that DOES exist
    elif not logged_in:
        return render(request, 'faculty_profile/no_login.html', context={'profile': profile,
                                                                         'office_hours': office_hours,
                                                                         'user_id': user_id})
    # if the logged in user is not visiting their own profile and the profile they're visiting DOES NOT exist
    elif user_id != logged_in and no_profile:
        return render(request, 'faculty_profile/not_ur_profile_no_profile.html', context={'user_id': user_id})
    # if the logged in user is not visiting their own profile, but the profile they're visiting exists
    elif user_id != logged_in:
        return render(request, 'faculty_profile/not_ur_profile.html', context={'profile': profile,
                                                                               'office_hours': office_hours,
                                                                               'user_id': user_id})
    # if the logged in user is visiting their own profile but they haven't created a profile yet
    elif no_profile:
        return render(request, 'faculty_profile/no_profile.html', context={'user_id': user_id})
    # if the logged user is on their own created profile
    else:
        return render(request, 'faculty_profile/index.html', context={'profile': profile,
                                                                      'office_hours': office_hours,
                                                                      'user_id': user_id})


def edit(request, user_id):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = EditProfileForm(request.POST, extra=request.POST.get('extra_field_count'), use_required_attribute=False)
        if 'add' in request.POST:
            print('you pressed add button')
            print('count: ' + str(request.POST.get('extra_field_count')))
            return render(request, 'faculty_profile/edit.html', {'form': form, 'user_id': user_id})
        if 'submit' in request.POST:
            print('you pressed submit button')
            if form.is_valid():
                print("valid!")

                # get a list of extra fields
                fields_not_wanted = ['faculty_id', 'location', 'phone', 'extra_field_count']
                fields_given = list(form.get_fields().keys())
                extra_fields = list(set(fields_not_wanted) ^ set(fields_given))

                # save faculty profile
                form = form.save()

                # find and select the corresponding profile
                profile = list(Profile.objects.filter(faculty_id=request.POST.get('faculty_id')))[0]

                # save extra fields (office hours)
                for i in range(len(extra_fields)):
                    hours_given = request.POST.get(extra_fields[i])
                    office_hour = OfficeHours.objects.create(faculty=profile, date_time=hours_given)
                    office_hour.save()

                return redirect(reverse('faculty_profile:index', kwargs={'user_id': request.POST.get('faculty_id')}))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = EditProfileForm()

    return render(request, 'faculty_profile/edit.html', {'form': form, 'user_id': user_id})


def syllabus(request, user_id):
    return HttpResponse('View will be connected to the syllabus app later')

faculty_profile/templates/faculty_profile/edit.html
<!DOCTYPE html>
<html lang="en">

<head>{% load static %}
    <meta charset="UTF-8">
    <title>Edit Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'faculty_profile/css/editProfile.css'%}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>

    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
          <h3 >UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
		    <a href="{% url 'login:logout_view' %}" class="btn btn-outline-light me-2">Logout</a>
            <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>
</head>

<body>
    <main class="editProfile">
        <div class="form-group text-center">
            <form method="post">{% csrf_token %}
                <div class="form-floating">
                    {{ form.as_p }}
                </div>
                <button name="add" id="add-another" class="button">Add New Box</button>
                <br>

                <button name="submit" class="button">Submit</button>

                <div id='empty-form'> {{ form.empty_form }}</div>
            </form>
        </div>
    </main>

    <script>
    let form_count = Number($("[name=extra_field_count]").val());
    // get extra form count so we know what index to use for the next item.

    $("#add-another").click(function() {
        form_count ++;

        let element = $('<input type="text"/>');
        element.attr('name', 'extra_field_' + form_count);
        $("#forms").append(element);
        // build element and append it to our forms container

        $("[name=extra_field_count]").val(form_count);
        // increment form count so our view knows to populate
        // that many fields for validation
    })
</script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

faculty_profile/templates/faculty_profile/index.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>Faculty Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'faculty_profile/css/index.css'%}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
          <h3 >UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
		    <a href="{% url 'login:logout_view' %}" class="btn btn-outline-light me-2">Logout</a>
            <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>

</head>
<body>
<div class="modal position-static modal-tour d-block py-2" tabindex="-2" role="dialog" id="modalTour" id="profileInfo">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-1 shadow">
      <div class="modal-body p-4">
        <h2 id="profileName" class="fw-bold mb-3">{{ profile.ID }}</h2>
        <ul class="d-grid gap-1 my-1 list-unstyled">
          <h2>Faculty Profile: {{user_id}}</h2>
          <li class="d-flex gap-4">
            <svg class="bi text-muted flex-shrink-0" width="68" height="68"><use xlink:href="#grid-fill"/></svg>
            <div>
              <h5 class="mb-0">Office Location:</h5>
              {{ profile.location }}
            </div>
          </li>
          <li class="d-flex gap-4">
            <svg class="bi text-warning flex-shrink-0" width="68" height="68"><use xlink:href="#bookmark-star"/></svg>
            <div>
              <h5 class="mb-0">Office Phone:</h5>
              {{ profile.phone }}
            </div>
          </li>
          <li class="d-flex gap-4">
            <svg class="bi text-warning flex-shrink-0" width="68" height="68"><use xlink:href="#bookmark-star"/></svg>
            <div>
              <h5 class="mb-0">Office Hours:</h5>
              {% for hour in office_hours %}
                {{ hour.date_time }} <br>
              {% endfor %}
            </div>
          </li>
        </ul>
        <a href="{% url 'faculty_profile:edit' user_id %}" class="btn btn-warning mt-6 w-100 mx-50">Profile Modifier</a>
        <br>
        <br>
        <a href="{% url 'syllabus_form:wizardWelcome' %}" class="btn btn-warning mt-6 w-100 mx-50"> Syllabus Wizard</a>
        <br>
        <br>
        <a href="{% url 'synthesizew:index' %}" class="btn btn-warning mt-6 w-100 mx-50"> Upload Syllabus</a>

      </div>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

faculty_profile/templates/faculty_profile/no_login.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>Faculty Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'faculty_profile/css/index.css'%}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
          <h3 >UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
            <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>

</head>
<body>
<div class="modal position-static modal-tour d-block py-2" tabindex="-2" role="dialog" id="modalTour" id="profileInfo">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-1 shadow">
      <div class="modal-body p-4">
        <h2 id="profileName" class="fw-bold mb-3">{{ profile.ID }}</h2>
        <ul class="d-grid gap-1 my-1 list-unstyled">
          <h2>Faculty Profile: {{user_id}}</h2>
          <li class="d-flex gap-4">
            <svg class="bi text-muted flex-shrink-0" width="68" height="68"><use xlink:href="#grid-fill"/></svg>
            <div>
              <h5 class="mb-0">Office Location:</h5>
              {{ profile.location }}
            </div>
          </li>
          <li class="d-flex gap-4">
            <svg class="bi text-warning flex-shrink-0" width="68" height="68"><use xlink:href="#bookmark-star"/></svg>
            <div>
              <h5 class="mb-0">Office Phone:</h5>
              {{ profile.phone }}
            </div>
          </li>
          <li class="d-flex gap-4">
            <svg class="bi text-warning flex-shrink-0" width="68" height="68"><use xlink:href="#bookmark-star"/></svg>
            <div>
              <h5 class="mb-0">Office Hours:</h5>
              {% for hour in office_hours %}
                {{ hour.date_time }} <br>
              {% endfor %}
            </div>
          </li>
        </ul>

      </div>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

faculty_profile/templates/faculty_profile/no_login_no_profile.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>No Faculty Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'faculty_profile/css/no_profile.css'%}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
          <h3 >UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
            <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>
</head>

<body>

    <main class="noProfile">
        <div class="container text-center">
        <br>
        <h1>Welcome {{ user.email }}</h1>
        <h2>Faculty Profile: {{user_id}} Does Not Exist </h2>
        </div>
    </main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

faculty_profile/templates/faculty_profile/no_profile.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>No Faculty Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'faculty_profile/css/no_profile.css'%}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
          <h3 >UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
		    <a href="{% url 'login:logout_view' %}" class="btn btn-outline-light me-2">Logout</a>
            <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>
</head>

<body>

    <main class="noProfile">
        <div class="container text-center">
        <br>
        <h1>Welcome {{ user.email }}</h1>
        <h2>Faculty Profile: {{user_id}} Does Not Exist </h2>
        <br>
        <br>

        <h3>Please create a faculty Profile </h3>
            <br>
        <a href="{% url 'faculty_profile:edit' user_id %}" class="btn btn-lg btn-dark ">Profile Modifier</a> <br>
        </div>
    </main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

faculty_profile/templates/faculty_profile/not_ur_profile.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>Faculty Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'faculty_profile/css/index.css'%}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
          <h3 >UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
            <a href="{% url 'login:logout_view' %}" class="btn btn-outline-light me-2">Logout</a>
            <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>

</head>
<body>
<div class="modal position-static modal-tour d-block py-2" tabindex="-2" role="dialog" id="modalTour" id="profileInfo">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-1 shadow">
      <div class="modal-body p-4">
        <h2 id="profileName" class="fw-bold mb-3">{{ profile.ID }}</h2>
        <ul class="d-grid gap-1 my-1 list-unstyled">
          <h2>Faculty Profile: {{user_id}}</h2>
          <li class="d-flex gap-4">
            <svg class="bi text-muted flex-shrink-0" width="68" height="68"><use xlink:href="#grid-fill"/></svg>
            <div>
              <h5 class="mb-0">Office Location:</h5>
              {{ profile.location }}
            </div>
          </li>
          <li class="d-flex gap-4">
            <svg class="bi text-warning flex-shrink-0" width="68" height="68"><use xlink:href="#bookmark-star"/></svg>
            <div>
              <h5 class="mb-0">Office Phone:</h5>
              {{ profile.phone }}
            </div>
          </li>
          <li class="d-flex gap-4">
            <svg class="bi text-warning flex-shrink-0" width="68" height="68"><use xlink:href="#bookmark-star"/></svg>
            <div>
              <h5 class="mb-0">Office Hours:</h5>
              {% for hour in office_hours %}
                {{ hour.date_time }} <br>
              {% endfor %}
            </div>
          </li>
        </ul>

      </div>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

faculty_profile/templates/faculty_profile/not_ur_profile_no_profile.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>No Faculty Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'faculty_profile/css/no_profile.css'%}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
          <h3 >UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
		    <a href="{% url 'login:logout_view' %}" class="btn btn-outline-light me-2">Logout</a>
            <a href="{% url 'homepage:index' %}" class="btn btn-warning">Home</a>
        </div>
      </div>
    </div>
  </header>
</head>

<body>

    <main class="noProfile">
        <div class="container text-center">
        <br>
        <h1>Welcome {{ user.email }}</h1>
        <h2>Faculty Profile: {{user_id}} Does Not Exist </h2>
        </div>
    </main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>