homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    path('search', views.search, name='search')
]

login/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'
urlpatterns = [

    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout_view'),
    path('', views.login_view, name='login'),

    path("password_reset/", views.password_reset_request, name="password_reset"),


]

syllabus/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include('login.urls')),
    path('syllabus_form/', include('syllabus_form.urls')),
    path('profile/', include('faculty_profile.urls')),
    path('dept_info/', include('dept_info.urls')),
    path('add/', include('synthesizew.urls')),
    path('search/', include('lookup.urls')),

    # Needed for password reset. ONLY WORKS IF THEY ARE IN THE PROJECT URL AND NOT IN APP URL
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="login/password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset/password_reset_complete.html'), name='password_reset_complete'),
]

homepage/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect


# Create your views here.
from django.urls import reverse


def index(request):
    return render(request, 'homepage/index.html', context={})


def search(request):
    return redirect(reverse('lookup:index'))

homepage/templates/homepage/index.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <meta charset="UTF-8">
    <title>UMBC Syllabus Synthesizer</title>
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/css/homepage.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body style="background-image: url('{% static "homepage/images/homepage.jpg"%}');">
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        <img src="">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <h3>UMBC Syllabus Synthesizer </h3>
        </ul>

        <div class="text-end">
            <a href="{% url 'login:login' %}" class="btn btn-outline-light me-2">Faculty Login</a>
		    <a href="{% url 'homepage:search' %}" class="btn btn-warning">Syllabus Search</a>
        </div>
      </div>
    </div>
  </header>

</body>
</html>